# Standard library modules imported by yt-dlp to ensure they are compiled and bundled by Nuitka
import ast
import asyncio
import base64
import bisect
import bz2
import calendar
import collections
import contextlib
import contextvars
import copy
import copyreg
import ctypes
import csv
import dataclasses
import datetime
import difflib
import dis
import email
import email.mime.audio
import email.mime.base
import email.mime.image
import email.mime.multipart
import email.mime.nonmultipart
import email.mime.text
import encodings
import enum
import fileinput
import fnmatch
import functools
import getpass
import gettext
import glob
import hashlib
import heapq
import hmac
import html
import html.entities
import html.parser
import http
import http.client
import http.cookiejar
import http.cookies
import importlib
import inspect
import ipaddress
import json
import keyword
import linecache
import locale
import logging
import lzma
import mimetypes
import netrc
import nturl2path
import opcode
import operator
import optparse
import pathlib
import pkgutil
import platform
import plistlib
import posixpath
import pyexpat
import queue
import quopri
import random
import re
import reprlib
import select
import selectors
import shlex
import shutil
import signal
import socket
import sqlite3
import ssl
import string
import stringprep
import struct
import subprocess
import sysconfig
import tarfile
import tempfile
import textwrap
import threading
import token
import tokenize
import traceback
import types
import typing
import unicodedata
import urllib
import urllib.parse
import urllib.request
import urllib.error
import urllib.response
import uuid
import warnings
import weakref
import webbrowser
import xml
import xml.etree.ElementTree
import zipfile
